
package soap.ws.artifact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "https://smsc.ru/sys/soap.php")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.BalanceResponse
     */
    @WebMethod(operationName = "get_balance", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "BalanceResponse", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public BalanceResponse getBalance(
            @WebParam(name = "balance", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Balance parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.SendResponse
     */
    @WebMethod(operationName = "send_sms", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "SendResponse", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public SendResponse sendSms(
            @WebParam(name = "send", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Send parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.Send2Response
     */
    @WebMethod(operationName = "send_sms2", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "Send2Response", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public Send2Response sendSms2(
            @WebParam(name = "send2", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Send2 parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.CostResponse
     */
    @WebMethod(operationName = "get_sms_cost", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "CostResponse", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public CostResponse getSmsCost(
            @WebParam(name = "cost", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Cost parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.Cost2Response
     */
    @WebMethod(operationName = "get_sms_cost2", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "Cost2Response", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public Cost2Response getSmsCost2(
            @WebParam(name = "cost2", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Cost2 parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.StatusResponse
     */
    @WebMethod(operationName = "get_status", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "StatusResponse", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public StatusResponse getStatus(
            @WebParam(name = "status", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Status parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns wsclient.Status2Response
     */
    @WebMethod(operationName = "get_status2", action = "https://smsc.ru/sys/soap.php")
    @WebResult(name = "Status2Response", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
    public Status2Response getStatus2(
            @WebParam(name = "status2", targetNamespace = "https://smsc.ru/sys/soap.php", partName = "parameters")
                    Status2 parameters);

}
